menu:
- {name: 'ABOUT', url: '/#'}
- {name: 'PUBLICATIONS', url: '/publications'}
- {name: 'CV', url: '/assets/doc/CV.pdf'}

# - {name: 'CONTACT', url: '/contact'}

# interests:
# - {keyword: 'Augmented Reality in Outdoor'}
# - {keyword: 'Human and Scene Understanding in Context'}
# - {keyword: 'Storytelling Generation and Representation'}

news:
- {date: '<em>May 2024</em>', text: 'Congratulations 🎉 our paper got conditionally accepted to Siggraph 24 in Denver, USA. See you at Denver!'}
- {date: '<em>May 2023</em>', text: 'Congratulations 🎉 our team got accepted to CHI23 in Hamburg, Germany. Honored to present our work on their behalf.'}
- {date: '<em>Aug 2021</em>', text: 'Will join DCXR Group in George Mason Universt starting to Fall 21.'}
# - {date: 'July 2021', text: 'My short paper (Facial Geometry Synthesis Using Locally Weighted Autoencoder) got accepted at CGI2021'}

honors:
- {text: 'Best Paper Award, Korea Computer Graphics Society (KCGS), 2019'}

services:
- {text: '<b>Seminar</b> Hong Kong Metropolitan University (HKMU) Oct, 2024'}
- {text: '<b>Invited Talk</b>, GAMES (Graphics And Mixed Environment Symposium) Jul, 2024'}


press:
- {text: 'Our augmented reality dragon project was featured by the <a href="https://www.youtube.com/watch?v=bVUmZRqHiX0&t=131s">ABC news Good Morning America</a>.'}

people:
- {name: 'Minyoung Kim', title: 'Ph.D. Student', department: 'Department of Computer Science', institution: 'George Mason University', institution_address: '4400 University Drive, Fairfax, VA', phone: '(000) 000-0000', email: 'mkim229@gmu.edu', office: 'Research Hall 405 in GMU', image: 'assets/images/realphoto-crop.jpg'}


# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/minyoung-mia-kim'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/minyoung-kim-4361b711b/'}
- {icon: 'google-scholar', link: 'https://www.linkedin.com/in/minyoung-kim-4361b711b/'}


contacts:
- {name: 'Minyoung Kim', title: 'Ph.D. Student', department: 'Department of Computer Science', institution: 'George Mason University', institution_address: '4400 University Drive, Fairfax, VA', phone: '(000) 000-0000', email: 'mkim229@gmu.edu', office: 'Research Hall 405 in GMU', image: 'assets/images/realphoto-crop.jpg'}
